[variables]
PHP_VERSION = "8.3"

[phases.setup]
nixPkgs = [
    'php83',
    'php83Extensions.gd',
    'php83Extensions.zip',
    'php83Extensions.pdo',
    'php83Extensions.pdo_mysql',
    'php83Extensions.mbstring',
    'php83Extensions.curl',
    'php83Extensions.xml',
    'php83Extensions.fileinfo',
    'php83Extensions.tokenizer',
    'php83Extensions.bcmath',
    'php83Extensions.ctype',
    'php83Extensions.dom',
    'php83Extensions.simplexml'
]

[phases.install]
cmds = [
    'php -v',
    'composer config platform.php 8.3.0',
    'composer install --optimize-autoloader --no-dev --no-interaction --no-scripts'
]

[phases.build]
cmds = [
    'php artisan storage:link || true',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'